# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='username',
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='apropos',
            field=models.TextField(blank=True, default="Je n'ai pas encore rempli ma description :)", null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='description',
            field=models.TextField(blank=True, default="Je n'ai pas encore rempli ma description :)", null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
