# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_auto_20160916_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='fb_profile',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='identite',
            field=models.ImageField(null=True, upload_to='identite/'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='ln_profile',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nbr_annonce',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nbr_cmd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nbr_livraison',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='tw_profile',
            field=models.URLField(default='', null=True),
        ),
    ]
