# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_auto_20160916_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='fb_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='identite',
            field=models.ImageField(blank=True, null=True, upload_to='identite/'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='ln_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='tw_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
