# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_auto_20160916_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='google_plus_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
