# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_auto_20170119_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('rue', models.CharField(default='', max_length=100)),
                ('cp', models.IntegerField()),
                ('ville', models.CharField(default='', max_length=100)),
                ('pays', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={},
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='nbr_annonce',
            new_name='nb_annonce',
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='nbr_cmd',
            new_name='nb_cmd',
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='nbr_livraison',
            new_name='nb_livraison',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='ville',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.Adresses'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='adresse mail'),
        ),
        migrations.AlterModelTable(
            name='utilisateurs',
            table='t_utilisateurs',
        ),
    ]
