# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_auto_20170119_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresses',
            name='adresse_principale',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='adresse',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='adresse',
            field=models.ManyToManyField(to='compte.Adresses'),
        ),
    ]
