# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_auto_20170121_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresses',
            new_name='Adresse',
        ),
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
    ]
