# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0011_auto_20170121_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='apropos',
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='adresse',
            field=models.ManyToManyField(blank=True, null=True, to='compte.Adresse'),
        ),
    ]
