# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0012_auto_20170121_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='fb_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='google_plus_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='ln_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nb_annonce',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nb_cmd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='nb_livraison',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='tw_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
